name: Mobile E2E Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./coordcamp-android

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Appium Tests
      run: node appium-tests/app-tests.mjs

    - name: Upload Test Report to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Appium_Mobile_Execution_Report
        path: coordcamp-android/Appium_Mobile_Execution_Report.xlsx
